export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
