export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const GET_ALL_VENDORS = "GET_ALL_VENDORS";
export const GET_ALL_VENDORS_SUCESS = "GET_ALL_VENDORS_SUCESS";
export const GET_ALL_VENDORS_FAILED = "GET_ALL_VENDORS_FAILED";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const LOGIN_VENDOR = "LOGIN_VENDOR";
export const VENDOR_SUCCESS = "VENDOR_SUCCESS";
export const VENDOR_FAILED = "VENDOR_FAILED";

export const VENDOR_SIGNIN = "VENDOR_SIGNIN";
export const VENDOR_SIGNIN_SUCCESS = "VENDOR_SIGNIN_SUCCESS";
export const VENDOR_SIGNIN_FAILED = "VENDOR_SIGNIN_FAILED";

export const GET_DETAIL_VENDOR = "GET_DETAIL_VENDOR";
export const GET_DETAIL_VENDOR_SUCESS = "GET_DETAIL_VENDOR_SUCESS";
export const GET_DETAIL_VENDOR_FAILED = "GET_DETAIL_VENDOR_FAILED";
//companydetail
